name: Build Windows EXE from .NET Project

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest # This tells GitHub Actions to run the build on a Windows machine.

    steps:
    # Step 1: Checkout the code from your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up the .NET SDK on the Windows runner
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0..x' # Adjust the .NET version to what your project uses

    # Step 3: Restore the project's dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the project in Release mode
    - name: Build the project
      run: dotnet build --configuration Release

    # Step 5: Publish the project to create a self-contained Windows executable (.exe)
    - name: Publish for Windows (win-x64)
      run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true

    # Step 6: Upload the .exe file as an artifact for download
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: |
          ./YourProjectName/bin/Release/net8.0/win-x64/publish/*
